### ISSUE TITLE
This isn't a 2008 Flash game, you don't need a help button

### ISSUE THREAD

**Issue by axelmortimer** [mel-gross/IDMt380-Alpha-Team#67]
Come on guys.

**Comment by Snibeti** [comment]
A note I'd like to add about the help button- 

This website should be intuitive enough that no help button is necessary, however your tools aren't labeled properly making it confusing and need trial and error to figure out what they do. 
See your coloring page: 
- the slider isnt labeled as being a means to zoom in and out of the canvas
- there is a random check box that I am unsure what the purpose of it is.)
- If I want a color not in the default palette, why do I have to click on an expanded menu, browse the color schemes, and then only be able to select the color. 

Overall not very helpful from a usability standpoint
